"""
Plot training metrics from a CSV file generated by train.py.
Usage: python plot_metrics.py --csv-file metrics.csv --output metrics_plot.png
"""
import argparse
import csv
import matplotlib.pyplot as plt


def plot_metrics(csv_file, output_file=None):
    """Load metrics from CSV and generate plots."""
    metrics = {
        'epoch': [],
        'train_loss': [],
        'train_acc': [],
        'val_loss': [],
        'val_acc': []
    }
    
    # Read CSV
    with open(csv_file, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            metrics['epoch'].append(int(row['epoch']))
            metrics['train_loss'].append(float(row['train_loss']))
            metrics['train_acc'].append(float(row['train_acc']))
            metrics['val_loss'].append(float(row['val_loss']))
            metrics['val_acc'].append(float(row['val_acc']))
    
    # Create plots
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    
    # Loss plot
    axes[0].plot(metrics['epoch'], metrics['train_loss'], label='Train Loss', marker='o')
    axes[0].plot(metrics['epoch'], metrics['val_loss'], label='Val Loss', marker='s')
    axes[0].set_xlabel('Epoch')
    axes[0].set_ylabel('Loss')
    axes[0].set_title('Training and Validation Loss')
    axes[0].legend()
    axes[0].grid(True)
    
    # Accuracy plot
    axes[1].plot(metrics['epoch'], metrics['train_acc'], label='Train Accuracy', marker='o')
    axes[1].plot(metrics['epoch'], metrics['val_acc'], label='Val Accuracy', marker='s')
    axes[1].set_xlabel('Epoch')
    axes[1].set_ylabel('Accuracy')
    axes[1].set_title('Training and Validation Accuracy')
    axes[1].legend()
    axes[1].grid(True)
    
    plt.tight_layout()
    
    if output_file:
        plt.savefig(output_file, dpi=150)
        print(f"Plot saved to {output_file}")
    else:
        plt.show()
    
    plt.close()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Plot training metrics from CSV')
    parser.add_argument('--csv-file', type=str, default='metrics.csv', help='Path to metrics CSV file')
    parser.add_argument('--output', type=str, default=None, help='Output image file (if None, display plot)')
    args = parser.parse_args()
    
    plot_metrics(args.csv_file, args.output)
